# Generated by Django 4.1.1 on 2022-09-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blog_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
